[package]
name = "matse_calendar"
version = "1.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = { version = "0.46.1", features = ["async" ]}
chrono = { version = "0.4.31", default-features = false, features = ["alloc","serde"] }
chrono-tz = "0.8.5"
ics = "0.5.8"
lazy_static = "1.4.0"
reqwest = { version = "0.11.23", features = ["json"] }
rocket = { version = "0.5.0", features = ["json"] }
serde = { version = "1.0.193", features = ["derive"] }
time = "0.3.31"
tokio = { version = "1.35.1", features = [] }
