[package]
name = "matse_calendar"
version = "1.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.44"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4", default-features = false, features = ["alloc","serde"] }
chrono-tz = "0.8.3"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
ics = "0.5"
rocket = { version = "0.5.0-rc.3", features = ["json"] }
time = "0.3"
