name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Read Version
        id: read_version
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: 'Cargo.toml'
          field: 'package.version'

      - name: Read Name
        id: read_name
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: 'Cargo.toml'
          field: 'package.name'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.read_name.outputs.value }}:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.read_name.outputs.value }}:${{ steps.read_version.outputs.value }}, ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.read_name.outputs.value }}:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
