name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v3

      - name: Semver
        id: semver
        uses: morbatex/cargo_semver_update@v1

      - uses: EndBug/add-and-commit@v9.1.1
        with:
          message: Changed version to ${{ steps.semver.outputs.new_version_with_v }}
          committer_name: GitHub Actions
          committer_email: actions@github.com

      - name: Read Name
        id: read_name
        uses: SebRollen/toml-action@v1.0.2
        with:
          file: 'Cargo.toml'
          field: 'package.name'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.read_name.outputs.value }}:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.read_name.outputs.value }}:${{ steps.semver.outputs.new_version }}, ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.read_name.outputs.value }}:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
